# ----------------------------
# Canvas
# ----------------------------
[canvas]
width = "896px"
height = "1200px"
background_color = "#FFFFFF"

[config_print]
dpi = 32

# ----------------------------
# Elements
# ----------------------------

[[element]]
id = 21
type = "draping_preview_base"
source_image = "images/image_mask_buttons.png"
z-index = 20

[[element]]
id = 11
type = "draping_preview_mask"
mask = "images/image_mask_0.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
content_artwork_offset_x = 10
content_artwork_offset_y = 10
content_artwork_scale = 1
content_artwork_rotation = 0
content_artwork_opacity = 1
content_levels_amplifier = 0
z-index = 10

[[element]]
id = 12
type = "draping_preview_mask"
mask = "images/image_mask_1.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
content_artwork_offset_x = 12
content_artwork_offset_y = 5
content_artwork_scale = 1
content_artwork_rotation = 10
content_artwork_opacity = 1
content_levels_amplifier = -62
z-index = 10

[[element]]
id = 13
type = "draping_preview_mask"
mask = "images/image_mask_2.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
content_artwork_offset_x = 0
content_artwork_offset_y = 60
content_artwork_scale = 1
content_artwork_rotation = 320
content_artwork_opacity = 1
content_levels_amplifier = -34
z-index = 10

[[element]]
id = 14
type = "draping_preview_mask"
mask = "images/image_mask_3.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
content_artwork_offset_x = 5
content_artwork_offset_y = 6
content_artwork_scale = 1
content_artwork_rotation = 90
content_artwork_opacity = 1
content_levels_amplifier = -50
z-index = 10

[[element]]
id = 1
type = "draping_preview_base"
source_image = "images/image_base.jpg"
z-index = 2
