# ----------------------------
# Canvas
# ----------------------------
[canvas]
width = "background_image_width"
height = "background_image_height"
background_image = "images/image_base.png"
background_color = "#FFFFFF"

[config_print]
dpi = 150

# ----------------------------
# Elements
# ----------------------------

[[element]]
id = 1
type = "draping_preview_mask"
mask = "images/image_mask_0.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
z-index = 3

[[element]]
id = 2
type = "draping_preview_mask"
mask = "images/image_mask_1.png"
suitable_content = "preview_artwork_draping"
content_blend_mode = "multiply"
content_artwork_offset_x = -260
content_artwork_offset_y = 330
content_artwork_rotation = -45
z-index = 3

[[element]]
id = 3
type = "draping_preview_base"
source_image = "images/image_mask.png"
z-index = 0
